import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { PatientWoundHistory } from '../services/woundlensApi';
import { Card, Pill, PrimaryButton } from '../components/Primitives';
import { colors, layout, typography } from '../theme';

export function PatientDetailScreen({ history, onOpenHistory, onStartScan }: { history: PatientWoundHistory; onOpenHistory: () => void; onStartScan: () => void }) {
  return <ScrollView contentContainerStyle={styles.page}><View style={styles.content}>
    <Card style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>{history.caseId.replace('case_', 'C')}</Text></View><View style={styles.profileCopy}><Text style={typography.title}>Dataset Case {history.caseId.replace('case_', '')}</Text><Text style={styles.meta}>{history.visits.length} available longitudinal visits</Text><Text style={styles.meta}>Dataset-derived record</Text></View><Pill tone="primary">DATASET</Pill></Card>
    <View style={styles.grid}><DetailMetric label="Baseline Visit" value={`Day ${history.previousVisit.day}`} detail={history.previousVisit.scene} /><DetailMetric label="Current Visit" value={`Day ${history.currentVisit.day}`} detail={history.currentVisit.scene} /><DetailMetric label="Model Change Score" value={history.analysis?.modelChangeScore.toFixed(4) ?? 'NOT RUN'} detail={history.analysis?.multimodalChange ?? 'Select visits to compare'} danger={history.analysis?.clinicalReviewRequired} /><DetailMetric label="Clinical Review" value={history.analysis ? (history.analysis.clinicalReviewRequired ? 'RECOMMENDED' : 'NOT REQUIRED') : 'NOT RUN'} detail="Model output after analysis" danger={history.analysis?.clinicalReviewRequired} /></View>
    <Card style={styles.notesCard}><Text style={typography.sectionTitle}>Case Record</Text><Text style={styles.noteText}>Choose a baseline and follow-up from the discovered dataset visits, or create a manual multimodal scan against a baseline.</Text></Card>
    <View style={styles.actions}><PrimaryButton icon="time-outline" onPress={onOpenHistory}>Wound History</PrimaryButton><PrimaryButton icon="scan-outline" onPress={onStartScan}>Scan Wound</PrimaryButton></View>
  </View></ScrollView>;
}

function DetailMetric({ label, value, detail, danger }: { label: string; value: string; detail: string; danger?: boolean }) { return <Card style={[styles.metricCard, danger && styles.dangerCard]}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, danger && styles.dangerText]}>{value}</Text><Text style={styles.metricDetail}>{detail}</Text></Card>; }
const styles = StyleSheet.create({ page: { padding: layout.pagePadding, alignItems: 'center' }, content: { width: '100%', maxWidth: 760, gap: 14 }, profileCard: { flexDirection: 'row', alignItems: 'center', gap: 16 }, avatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 18, fontWeight: '900', color: colors.primary }, profileCopy: { flex: 1 }, meta: { ...typography.body, color: colors.textMuted }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, metricCard: { flex: 1, minWidth: 240, gap: 6 }, dangerCard: { backgroundColor: colors.dangerSoft, borderColor: '#ffc8c8' }, metricLabel: { ...typography.label }, metricValue: { fontSize: 22, lineHeight: 28, fontWeight: '900', color: colors.text }, dangerText: { color: colors.danger }, metricDetail: { ...typography.caption }, notesCard: { gap: 8 }, noteText: { ...typography.body, color: colors.textMuted }, actions: { gap: 12 } });
