import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { PatientWoundHistory, mediaUrl } from '../services/woundlensApi';
import { Card, Pill, PrimaryButton } from '../components/Primitives';
import { colors, layout, typography } from '../theme';

export function WoundHistoryScreen({ history, onOpenResult }: { history: PatientWoundHistory; onOpenResult: () => void }) {
  return <ScrollView contentContainerStyle={styles.page}><View style={styles.content}>
    <Card style={styles.reportCard}><View style={styles.reportTop}><View><Text style={styles.reportId}>DATASET CASE: {history.caseId.toUpperCase()}</Text><Text style={typography.title}>Wound History</Text><Text style={styles.meta}>{history.visits.length} discovered visits</Text></View><Pill tone="primary">DATASET</Pill></View><View style={styles.rule} /><View style={styles.visitPair}><VisitTile title="Baseline Visit" visit={history.previousVisit} /><VisitTile title="Current Visit" visit={history.currentVisit} current /></View></Card>
    <Card style={styles.timelineCard}><Text style={typography.sectionTitle}>Longitudinal Timeline</Text>{history.visits.map((visit) => <Pressable key={visit.id} onPress={onOpenResult} style={styles.timelineRow}><View style={[styles.timelineDot, visit.day === history.currentVisit.day && styles.currentDot]} /><View style={styles.timelineText}><Text style={styles.visitTitle}>{visit.caseId} / Day {visit.day}</Text><Text style={styles.meta}>{visit.scene}</Text></View><Text style={styles.openText}>Compare</Text></Pressable>)}</Card>
    <PrimaryButton icon="analytics-outline" onPress={onOpenResult}>Select Visits to Analyze</PrimaryButton>
  </View></ScrollView>;
}
function VisitTile({ title, visit, current }: { title: string; visit: PatientWoundHistory['previousVisit']; current?: boolean }) { const source = mediaUrl(visit, 'rgb'); return <View style={[styles.visitTile, current && styles.currentVisit]}><View style={styles.thumbnail}>{source ? <Image source={{ uri: source }} style={styles.image} resizeMode="cover" /> : <Text style={styles.empty}>RGB unavailable</Text>}</View><Text style={styles.visitTitle}>{title}</Text><Text style={styles.meta}>{visit.caseId} / Day {visit.day}</Text></View>; }
const styles = StyleSheet.create({ page: { padding: layout.pagePadding, alignItems: 'center' }, content: { width: '100%', maxWidth: 720, gap: 16 }, reportCard: { gap: 16 }, reportTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, reportId: { ...typography.label, color: colors.primary, marginBottom: 8 }, meta: { ...typography.body, color: colors.textMuted }, rule: { height: 1, backgroundColor: colors.border }, visitPair: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, visitTile: { flex: 1, minWidth: 240, borderRadius: 8, borderWidth: 1, borderColor: colors.border, padding: 12, gap: 8 }, currentVisit: { borderColor: colors.primary }, thumbnail: { height: 130, borderRadius: 8, overflow: 'hidden', backgroundColor: '#dfe6ef', alignItems: 'center', justifyContent: 'center' }, image: { width: '100%', height: '100%' }, empty: { ...typography.caption }, visitTitle: { ...typography.subtitle }, timelineCard: { gap: 12 }, timelineRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12 }, timelineDot: { width: 14, height: 14, borderRadius: 7, backgroundColor: colors.borderStrong }, currentDot: { backgroundColor: colors.primary }, timelineText: { flex: 1 }, openText: { ...typography.body, color: colors.primary, fontWeight: '800' } });
