# -*- coding: utf-8 -*-
"""WoundLens_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmIOLoqE48o5BLF5OMoEn6cds3uXsRLT
"""

# ============================================================
# WOUNDLENS MODEL — STEP 1
# Upload and extract the local result.zip dataset
#
# This step ONLY:
#   1. Uploads result.zip from your computer
#   2. Extracts it
#   3. Finds all case folders
#
# NO training yet.
# ============================================================

from google.colab import files
import os
import zipfile


# ------------------------------------------------------------
# 1. Upload result.zip from your computer
# ------------------------------------------------------------

uploaded = files.upload()

ZIP_NAME = "result.zip"

if ZIP_NAME not in uploaded:
    raise FileNotFoundError(
        "Please upload the file named exactly: result.zip"
    )

print("\nUpload complete:", ZIP_NAME)


# ------------------------------------------------------------
# 2. Create WoundLens model workspace
# ------------------------------------------------------------

PROJECT_ROOT = "/content/WoundLens_Model"
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
EXTRACT_DIR = os.path.join(DATA_DIR, "processed")

os.makedirs(EXTRACT_DIR, exist_ok=True)

print("Workspace:", PROJECT_ROOT)


# ------------------------------------------------------------
# 3. Extract result.zip
# ------------------------------------------------------------

ZIP_PATH = f"/content/{ZIP_NAME}"

print("\nExtracting dataset...")

with zipfile.ZipFile(ZIP_PATH, "r") as zip_file:
    zip_file.extractall(EXTRACT_DIR)

print("Extraction complete.")


# ------------------------------------------------------------
# 4. Automatically locate case_* folders
#
# We do NOT assume whether the ZIP contains:
#
# result/case_1/
# results/case_1/
# case_1/
#
# The code discovers them automatically.
# ------------------------------------------------------------

case_paths = []

for root, dirs, filenames in os.walk(EXTRACT_DIR):

    for dirname in dirs:

        if dirname.startswith("case_"):

            full_path = os.path.join(root, dirname)

            # Avoid accidentally collecting nested duplicates.
            if os.path.basename(full_path).startswith("case_"):
                case_paths.append(full_path)


# Remove duplicates.
case_paths = sorted(
    set(case_paths),
    key=lambda path: (
        int(os.path.basename(path).split("_")[1])
        if os.path.basename(path).split("_")[1].isdigit()
        else 999999
    )
)


# ------------------------------------------------------------
# 5. Show detected cases
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("CASES DETECTED")
print("=" * 60)

print("Total cases:", len(case_paths))

for path in case_paths:
    print(
        os.path.basename(path),
        "->",
        path
    )


# ------------------------------------------------------------
# 6. Quick count of day folders
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("QUICK DAY CHECK")
print("=" * 60)

for case_path in case_paths:

    days = [
        name
        for name in os.listdir(case_path)
        if name.startswith("day_")
        and os.path.isdir(
            os.path.join(case_path, name)
        )
    ]

    # Sort day_1, day_7, day_28, etc. numerically.
    days = sorted(
        days,
        key=lambda x: (
            int(x.split("_")[1])
            if x.split("_")[1].isdigit()
            else 999999
        )
    )

    print(
        f"{os.path.basename(case_path):<10}"
        f" visits={len(days):<3}"
        f" {days}"
    )


# ------------------------------------------------------------
# 7. Final status
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("WOUNDLENS MODEL — STEP 1 COMPLETE")
print("=" * 60)

print("ZIP extraction : PASS")
print("Cases detected :", len(case_paths))

if len(case_paths) == 0:
    print("\nWARNING: No case_* folders were detected.")
else:
    print("\nDataset structure is ready for inventory.")

# ============================================================
# WOUNDLENS — FIX UPLOADED ZIP NAME
# DO NOT upload the dataset again.
# ============================================================

import os
import glob

# Find ZIP files already uploaded to Colab
zip_files = glob.glob("/content/*.zip")

print("ZIP files found:")
for f in zip_files:
    print(" -", f)

if not zip_files:
    raise FileNotFoundError(
        "No ZIP file found in /content."
    )

# Prefer the newly uploaded results ZIP
matching = [
    f for f in zip_files
    if "result" in os.path.basename(f).lower()
]

if matching:
    ZIP_PATH = max(
        matching,
        key=os.path.getsize
    )
else:
    ZIP_PATH = max(
        zip_files,
        key=os.path.getsize
    )

print("\nUsing dataset:")
print(ZIP_PATH)

print(
    "Size:",
    round(os.path.getsize(ZIP_PATH) / (1024 ** 2), 2),
    "MB"
)

print("\nREADY_TO_EXTRACT")

# ============================================================
# WOUNDLENS MODEL — STEP 2
# Extract existing results.zip and scan the complete dataset.
#
# NO model training yet.
# This tells us exactly how many cases/days/scenes we have.
# ============================================================

import os
import zipfile

# ZIP_PATH already points to:
# /content/results.zip

PROJECT_ROOT = "/content/WoundLens_Model"
DATASET_DIR = os.path.join(PROJECT_ROOT, "dataset")

os.makedirs(DATASET_DIR, exist_ok=True)


# ------------------------------------------------------------
# 1. Extract dataset
# ------------------------------------------------------------

print("Extracting dataset...")

with zipfile.ZipFile(ZIP_PATH, "r") as zip_file:
    zip_file.extractall(DATASET_DIR)

print("Extraction complete.")


# ------------------------------------------------------------
# 2. Find all case folders
# ------------------------------------------------------------

case_paths = []

for root, dirs, files in os.walk(DATASET_DIR):

    for dirname in dirs:

        if not dirname.startswith("case_"):
            continue

        path = os.path.join(root, dirname)

        # A real case folder should contain day_* folders.
        try:
            children = os.listdir(path)
        except Exception:
            continue

        if any(
            name.startswith("day_")
            for name in children
        ):
            case_paths.append(path)


# Remove duplicates
case_paths = list(set(case_paths))


# ------------------------------------------------------------
# 3. Numeric sorting helper
# ------------------------------------------------------------

def extract_number(name):

    try:
        return int(name.split("_")[-1])

    except Exception:
        return 999999


case_paths = sorted(
    case_paths,
    key=lambda p: extract_number(
        os.path.basename(p)
    )
)


# ------------------------------------------------------------
# 4. Build dataset inventory
# ------------------------------------------------------------

inventory = []

for case_path in case_paths:

    case_name = os.path.basename(case_path)

    days = [
        name
        for name in os.listdir(case_path)
        if name.startswith("day_")
        and os.path.isdir(
            os.path.join(case_path, name)
        )
    ]

    days = sorted(
        days,
        key=extract_number
    )

    scene_paths = []
    multimodal_scenes = []

    for day in days:

        day_path = os.path.join(
            case_path,
            day
        )

        # Scene number can vary:
        # scene_1, scene_2, scene_4, etc.
        for root, dirs, files in os.walk(day_path):

            if not os.path.basename(root).startswith("scene_"):
                continue

            scene_paths.append(root)

            file_set = set(files)

            # Minimum modalities required for our prototype
            if {
                "photo.png",
                "thermal.png",
                "depth.png"
            }.issubset(file_set):

                multimodal_scenes.append(root)


    inventory.append({

        "case": case_name,

        "path": case_path,

        "days": days,

        "num_days": len(days),

        "num_scenes": len(scene_paths),

        "multimodal_scenes":
            len(multimodal_scenes)
    })


# ------------------------------------------------------------
# 5. Rank useful longitudinal cases
# ------------------------------------------------------------

ranked_cases = sorted(
    inventory,
    key=lambda item: (
        item["num_days"],
        item["multimodal_scenes"],
        item["num_scenes"]
    ),
    reverse=True
)


# ------------------------------------------------------------
# 6. Print summary
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("DATASET SUMMARY")
print("=" * 75)

print("Cases detected:", len(inventory))

print(
    "Total visits:",
    sum(x["num_days"] for x in inventory)
)

print(
    "Total scenes:",
    sum(x["num_scenes"] for x in inventory)
)

print(
    "Multimodal scenes:",
    sum(x["multimodal_scenes"] for x in inventory)
)


# ------------------------------------------------------------
# 7. Show longitudinal cases
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("LONGITUDINAL CASES")
print("=" * 75)

longitudinal_cases = [
    item
    for item in ranked_cases
    if item["num_days"] > 1
]

for item in longitudinal_cases:

    print(
        f'{item["case"]:<10} | '
        f'Days: {item["num_days"]:<2} | '
        f'Scenes: {item["num_scenes"]:<2} | '
        f'Multimodal: {item["multimodal_scenes"]:<2} | '
        f'{item["days"]}'
    )


# ------------------------------------------------------------
# 8. Select 20 cases for FAST prototype
# ------------------------------------------------------------
# We prioritize longitudinal cases first.
# Remaining slots are filled with other usable cases.

selected_cases = ranked_cases[:20]


print("\n" + "=" * 75)
print("SELECTED 20 PROTOTYPE CASES")
print("=" * 75)

for item in selected_cases:

    print(
        f'{item["case"]:<10} '
        f'visits={item["num_days"]:<2} '
        f'multimodal={item["multimodal_scenes"]}'
    )


# ------------------------------------------------------------
# 9. Best demo candidate
# ------------------------------------------------------------

if longitudinal_cases:

    best_demo_case = longitudinal_cases[0]

    print("\n" + "=" * 75)
    print("BEST LONGITUDINAL DEMO CANDIDATE")
    print("=" * 75)

    print("Case :", best_demo_case["case"])
    print("Days :", best_demo_case["days"])
    print("Path :", best_demo_case["path"])


# ------------------------------------------------------------
# 10. Complete
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("WOUNDLENS MODEL — STEP 2 COMPLETE")
print("=" * 75)

print("Extraction : PASS")
print("Inventory  : PASS")

# ============================================================
# WOUNDLENS MODEL — STEP 3
# Build a multimodal feature table from:
#   RGB + Thermal + Depth
#
# IMPORTANT:
# These are image-level technical features.
# They are NOT yet clinical wound measurements.
#
# NO healing labels are invented.
# NO model is trained in this step.
# ============================================================

import os
import cv2
import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. Helper functions
# ------------------------------------------------------------

def extract_case_number(case_name):
    """case_17 -> 17"""
    try:
        return int(case_name.split("_")[1])
    except Exception:
        return None


def extract_day_number(day_name):
    """day_156 -> 156"""
    try:
        return int(day_name.split("_")[1])
    except Exception:
        return None


def load_rgb(path):
    """Load normal RGB image."""
    image = cv2.imread(path, cv2.IMREAD_COLOR)

    if image is None:
        return None

    return cv2.cvtColor(
        image,
        cv2.COLOR_BGR2RGB
    )


def load_grayscale(path):
    """
    Load an image and convert it to grayscale.

    NOTE:
    thermal.png and depth.png in this processed dataset
    are rendered 8-bit images.

    Their pixel values are NOT treated as:
    - actual temperature in °C
    - physical wound depth
    """

    image = cv2.imread(
        path,
        cv2.IMREAD_COLOR
    )

    if image is None:
        return None

    return cv2.cvtColor(
        image,
        cv2.COLOR_BGR2GRAY
    )


def image_statistics(image):
    """Basic intensity statistics."""

    return {
        "mean": float(np.mean(image)),
        "std": float(np.std(image)),
        "min": float(np.min(image)),
        "max": float(np.max(image)),
        "p25": float(np.percentile(image, 25)),
        "p50": float(np.percentile(image, 50)),
        "p75": float(np.percentile(image, 75)),
    }


# ------------------------------------------------------------
# 2. Build scene-level feature records
# ------------------------------------------------------------

records = []

for case in inventory:

    case_name = case["case"]
    case_path = case["path"]

    for day_name in case["days"]:

        day_number = extract_day_number(day_name)

        day_path = os.path.join(
            case_path,
            day_name
        )

        # Find all scene folders recursively.
        for root, dirs, files in os.walk(day_path):

            if not os.path.basename(root).startswith("scene_"):
                continue

            file_set = set(files)

            # We only use scenes having all 3 modalities.
            required = {
                "photo.png",
                "thermal.png",
                "depth.png"
            }

            if not required.issubset(file_set):
                continue


            # ------------------------------------------------
            # Load modalities
            # ------------------------------------------------

            rgb = load_rgb(
                os.path.join(
                    root,
                    "photo.png"
                )
            )

            thermal = load_grayscale(
                os.path.join(
                    root,
                    "thermal.png"
                )
            )

            depth = load_grayscale(
                os.path.join(
                    root,
                    "depth.png"
                )
            )

            if (
                rgb is None
                or thermal is None
                or depth is None
            ):
                continue


            # ------------------------------------------------
            # RGB statistics
            # ------------------------------------------------

            r = rgb[:, :, 0]
            g = rgb[:, :, 1]
            b = rgb[:, :, 2]

            # ------------------------------------------------
            # Thermal/depth rendered-image statistics
            # ------------------------------------------------

            thermal_stats = image_statistics(
                thermal
            )

            depth_stats = image_statistics(
                depth
            )


            # ------------------------------------------------
            # Store record
            # ------------------------------------------------

            records.append({

                "case": case_name,

                "case_number":
                    extract_case_number(case_name),

                "day":
                    day_number,

                "scene":
                    os.path.basename(root),

                "path":
                    root,

                # RGB
                "rgb_r_mean":
                    float(np.mean(r)),

                "rgb_g_mean":
                    float(np.mean(g)),

                "rgb_b_mean":
                    float(np.mean(b)),

                "rgb_r_std":
                    float(np.std(r)),

                "rgb_g_std":
                    float(np.std(g)),

                "rgb_b_std":
                    float(np.std(b)),

                # Thermal
                "thermal_mean":
                    thermal_stats["mean"],

                "thermal_std":
                    thermal_stats["std"],

                "thermal_p25":
                    thermal_stats["p25"],

                "thermal_p50":
                    thermal_stats["p50"],

                "thermal_p75":
                    thermal_stats["p75"],

                # Depth rendered image
                "depth_mean":
                    depth_stats["mean"],

                "depth_std":
                    depth_stats["std"],

                "depth_p25":
                    depth_stats["p25"],

                "depth_p50":
                    depth_stats["p50"],

                "depth_p75":
                    depth_stats["p75"],
            })


# ------------------------------------------------------------
# 3. Create DataFrame
# ------------------------------------------------------------

features_df = pd.DataFrame(
    records
)

print("=" * 70)
print("MULTIMODAL FEATURE DATASET")
print("=" * 70)

print("Rows:", len(features_df))
print("Columns:", len(features_df.columns))

display(
    features_df.head(10)
)


# ------------------------------------------------------------
# 4. Check longitudinal coverage
# ------------------------------------------------------------

case_visit_counts = (
    features_df
    .groupby("case")["day"]
    .nunique()
    .sort_values(ascending=False)
)

print("\n" + "=" * 70)
print("MULTIMODAL VISITS PER CASE")
print("=" * 70)

print(
    case_visit_counts[
        case_visit_counts > 1
    ]
)


# ------------------------------------------------------------
# 5. Save feature dataset
# ------------------------------------------------------------

OUTPUT_CSV = (
    "/content/WoundLens_Model/"
    "multimodal_features.csv"
)

features_df.to_csv(
    OUTPUT_CSV,
    index=False
)

print("\nSaved:")
print(OUTPUT_CSV)


# ------------------------------------------------------------
# 6. Final status
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("WOUNDLENS MODEL — STEP 3 COMPLETE")
print("=" * 70)

print(
    "Usable multimodal scenes:",
    len(features_df)
)

print(
    "Longitudinal multimodal cases:",
    int(
        (
            case_visit_counts > 1
        ).sum()
    )
)

print("\nIMPORTANT:")
print(
    "No healing labels have been invented.\n"
    "The next step will compare the SAME patient across visits."
)

# ============================================================
# WOUNDLENS MODEL — STEP 4
# Build longitudinal visit-to-visit change features.
#
# PURPOSE:
# Compare the SAME patient across visits.
#
# IMPORTANT:
# We are measuring multimodal CHANGE.
# We are NOT claiming that change = healing or infection.
# ============================================================

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. Select numerical multimodal features
# ------------------------------------------------------------

feature_columns = [
    # RGB
    "rgb_r_mean",
    "rgb_g_mean",
    "rgb_b_mean",
    "rgb_r_std",
    "rgb_g_std",
    "rgb_b_std",

    # Thermal rendered image
    "thermal_mean",
    "thermal_std",
    "thermal_p25",
    "thermal_p50",
    "thermal_p75",

    # Depth rendered image
    "depth_mean",
    "depth_std",
    "depth_p25",
    "depth_p50",
    "depth_p75",
]


# ------------------------------------------------------------
# 2. Sort by patient and acquisition day
# ------------------------------------------------------------

df_sorted = (
    features_df
    .sort_values(
        ["case", "day"]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 3. Build visit-to-visit pairs
#
# Example:
#
# case_17
# day_1  -> day_58
# day_58 -> day_72
# day_72 -> day_79
# ------------------------------------------------------------

change_records = []

for case_name, group in df_sorted.groupby("case"):

    group = (
        group
        .sort_values("day")
        .reset_index(drop=True)
    )

    # Need at least two visits.
    if len(group) < 2:
        continue

    for i in range(1, len(group)):

        previous = group.iloc[i - 1]
        current = group.iloc[i]

        record = {
            "case": case_name,
            "previous_day": int(previous["day"]),
            "current_day": int(current["day"]),
            "days_between":
                int(current["day"] - previous["day"]),
        }


        # ----------------------------------------------------
        # Calculate absolute and percentage change
        # ----------------------------------------------------

        for feature in feature_columns:

            prev_value = float(previous[feature])
            curr_value = float(current[feature])

            absolute_change = (
                curr_value - prev_value
            )

            # Prevent division-by-zero problems.
            denominator = (
                abs(prev_value)
                if abs(prev_value) > 1e-6
                else 1e-6
            )

            percentage_change = (
                absolute_change
                / denominator
            ) * 100.0


            record[
                f"{feature}_delta"
            ] = absolute_change

            record[
                f"{feature}_pct_change"
            ] = percentage_change


        change_records.append(record)


# ------------------------------------------------------------
# 4. Create longitudinal DataFrame
# ------------------------------------------------------------

changes_df = pd.DataFrame(
    change_records
)

print("=" * 70)
print("LONGITUDINAL CHANGE DATASET")
print("=" * 70)

print(
    "Visit-to-visit comparisons:",
    len(changes_df)
)

print(
    "Cases represented:",
    changes_df["case"].nunique()
)

display(
    changes_df[
        [
            "case",
            "previous_day",
            "current_day",
            "days_between"
        ]
    ].head(20)
)


# ------------------------------------------------------------
# 5. Build feature matrix for change scoring
#
# We use percentage changes because different modalities
# have different raw numerical ranges.
# ------------------------------------------------------------

change_feature_columns = [
    f"{feature}_pct_change"
    for feature in feature_columns
]

X = (
    changes_df[
        change_feature_columns
    ]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)


# ------------------------------------------------------------
# 6. Robust normalization
#
# StandardScaler makes the different feature ranges comparable.
# ------------------------------------------------------------

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)


# ------------------------------------------------------------
# 7. Calculate multimodal change magnitude
#
# Euclidean distance from "no change".
#
# Larger score =
# larger overall difference between visits.
#
# NOTE:
# Large change does NOT automatically mean worsening.
# ------------------------------------------------------------

raw_change_score = np.sqrt(
    np.mean(
        np.square(X_scaled),
        axis=1
    )
)

changes_df[
    "multimodal_change_score"
] = raw_change_score


# ------------------------------------------------------------
# 8. Convert score into simple prototype categories
#
# These are DATA-RELATIVE categories,
# NOT clinical severity categories.
# ------------------------------------------------------------

low_threshold = np.percentile(
    raw_change_score,
    33
)

high_threshold = np.percentile(
    raw_change_score,
    67
)


def categorize_change(score):

    if score < low_threshold:
        return "LOW CHANGE"

    elif score < high_threshold:
        return "MODERATE CHANGE"

    else:
        return "HIGH CHANGE"


changes_df[
    "change_category"
] = changes_df[
    "multimodal_change_score"
].apply(
    categorize_change
)


# ------------------------------------------------------------
# 9. Rank most changed visit pairs
# ------------------------------------------------------------

ranked_changes = (
    changes_df
    .sort_values(
        "multimodal_change_score",
        ascending=False
    )
)


print("\n" + "=" * 70)
print("TOP MULTIMODAL CHANGES")
print("=" * 70)

display(
    ranked_changes[
        [
            "case",
            "previous_day",
            "current_day",
            "days_between",
            "multimodal_change_score",
            "change_category"
        ]
    ].head(15)
)


# ------------------------------------------------------------
# 10. Save the longitudinal feature table
# ------------------------------------------------------------

OUTPUT_PATH = (
    "/content/WoundLens_Model/"
    "longitudinal_changes.csv"
)

changes_df.to_csv(
    OUTPUT_PATH,
    index=False
)

print("\nSaved:")
print(OUTPUT_PATH)


# ------------------------------------------------------------
# 11. Show one example case trajectory
# ------------------------------------------------------------

# Pick a strong longitudinal case automatically.
case_counts = (
    changes_df["case"]
    .value_counts()
)

DEMO_CASE = case_counts.index[0]

demo = (
    changes_df[
        changes_df["case"] == DEMO_CASE
    ]
    .sort_values("current_day")
)


print("\n" + "=" * 70)
print("DEMO CASE TRAJECTORY")
print("=" * 70)

print("Selected:", DEMO_CASE)

display(
    demo[
        [
            "previous_day",
            "current_day",
            "days_between",
            "multimodal_change_score",
            "change_category"
        ]
    ]
)


# ------------------------------------------------------------
# 12. Final status
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("WOUNDLENS MODEL — STEP 4 COMPLETE")
print("=" * 70)

print(
    "Visit comparisons:",
    len(changes_df)
)

print(
    "Patients compared:",
    changes_df["case"].nunique()
)

print(
    "Demo case:",
    DEMO_CASE
)

print("\nIMPORTANT:")
print(
    "The score represents the magnitude of change between visits.\n"
    "It is NOT yet a validated healing or worsening prediction."
)

# ============================================================
# WOUNDLENS — STEP 5
# Create visual longitudinal progression dashboard
#
# Demo case: case_12
#
# Shows:
# RGB | Thermal | Depth
# across all available visits.
#
# This is designed for the hackathon demonstration.
# ============================================================

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# 1. Select demo case
# ------------------------------------------------------------

DEMO_CASE = "case_12"

demo_rows = (
    features_df[
        features_df["case"] == DEMO_CASE
    ]
    .sort_values("day")
    .reset_index(drop=True)
)

print("Demo case:", DEMO_CASE)
print("Available multimodal visits:", len(demo_rows))
print("Days:", demo_rows["day"].tolist())


# ------------------------------------------------------------
# 2. Image loader
# ------------------------------------------------------------

def load_display_image(path):

    image = cv2.imread(path)

    if image is None:
        return None

    return cv2.cvtColor(
        image,
        cv2.COLOR_BGR2RGB
    )


# ------------------------------------------------------------
# 3. Create progression grid
#
# ROWS:
# RGB
# Thermal
# Depth
#
# COLUMNS:
# Visit days
# ------------------------------------------------------------

num_visits = len(demo_rows)

fig, axes = plt.subplots(
    3,
    num_visits,
    figsize=(4 * num_visits, 11)
)

# Handle rare case of only one visit
if num_visits == 1:
    axes = np.array(axes).reshape(3, 1)


for col, (_, row) in enumerate(
    demo_rows.iterrows()
):

    scene_path = row["path"]
    day = int(row["day"])

    paths = {
        "RGB": os.path.join(
            scene_path,
            "photo.png"
        ),

        "Thermal": os.path.join(
            scene_path,
            "thermal.png"
        ),

        "Depth": os.path.join(
            scene_path,
            "depth.png"
        ),
    }


    # --------------------------------------------------------
    # RGB
    # --------------------------------------------------------

    rgb = load_display_image(
        paths["RGB"]
    )

    axes[0, col].imshow(rgb)

    axes[0, col].set_title(
        f"Day {day}",
        fontsize=15,
        fontweight="bold"
    )

    axes[0, col].axis("off")


    # --------------------------------------------------------
    # Thermal
    # --------------------------------------------------------

    thermal = load_display_image(
        paths["Thermal"]
    )

    axes[1, col].imshow(
        thermal
    )

    axes[1, col].axis("off")


    # --------------------------------------------------------
    # Depth
    # --------------------------------------------------------

    depth = load_display_image(
        paths["Depth"]
    )

    axes[2, col].imshow(
        depth
    )

    axes[2, col].axis("off")


# ------------------------------------------------------------
# 4. Row labels
# ------------------------------------------------------------

axes[0, 0].set_ylabel(
    "RGB",
    fontsize=16,
    fontweight="bold"
)

axes[1, 0].set_ylabel(
    "THERMAL",
    fontsize=16,
    fontweight="bold"
)

axes[2, 0].set_ylabel(
    "DEPTH",
    fontsize=16,
    fontweight="bold"
)


# ------------------------------------------------------------
# 5. Title
# ------------------------------------------------------------

fig.suptitle(
    f"WoundLens — Longitudinal Multimodal Monitoring\n{DEMO_CASE}",
    fontsize=20,
    fontweight="bold"
)

plt.tight_layout(
    rect=[0, 0, 1, 0.93]
)


# ------------------------------------------------------------
# 6. Save dashboard
# ------------------------------------------------------------

OUTPUT_IMAGE = (
    "/content/WoundLens_Model/"
    "case_12_progression_dashboard.png"
)

plt.savefig(
    OUTPUT_IMAGE,
    dpi=200,
    bbox_inches="tight"
)

plt.show()

print("\nDashboard saved:")
print(OUTPUT_IMAGE)


# ------------------------------------------------------------
# 7. Clean progression scores
# ------------------------------------------------------------

clean_changes = changes_df[
    changes_df["days_between"] > 0
].copy()

case_changes = (
    clean_changes[
        clean_changes["case"] == DEMO_CASE
    ]
    .sort_values("current_day")
)


print("\n" + "=" * 65)
print("VISIT-TO-VISIT CHANGE")
print("=" * 65)

for _, row in case_changes.iterrows():

    print(
        f'Day {int(row["previous_day"])}'
        f' → Day {int(row["current_day"])}'
        f' | Score: {row["multimodal_change_score"]:.2f}'
        f' | {row["change_category"]}'
    )


print("\n" + "=" * 65)
print("WOUNDLENS — STEP 5 COMPLETE")
print("=" * 65)

print("Progression dashboard : PASS")
print("Demo patient          :", DEMO_CASE)

# ============================================================
# WOUNDLENS MODEL — STEP 6
# Train a multimodal change/anomaly model
#
# MODEL:
# Isolation Forest
#
# PURPOSE:
# Learn the distribution of longitudinal multimodal changes
# and identify unusual/high-change follow-up visits.
#
# IMPORTANT:
# This is NOT a clinical healing classifier.
# ============================================================

import os
import joblib
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest


# ------------------------------------------------------------
# 1. Remove invalid same-day comparisons
# ------------------------------------------------------------

model_df = changes_df[
    changes_df["days_between"] > 0
].copy()

print("Valid longitudinal comparisons:", len(model_df))
print("Patients:", model_df["case"].nunique())


# ------------------------------------------------------------
# 2. Features used by model
# ------------------------------------------------------------

model_features = [
    f"{feature}_pct_change"
    for feature in feature_columns
]

X = (
    model_df[model_features]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)


# ------------------------------------------------------------
# 3. Scale features
# ------------------------------------------------------------

model_scaler = StandardScaler()

X_scaled = model_scaler.fit_transform(X)


# ------------------------------------------------------------
# 4. Train Isolation Forest
#
# This learns what typical multimodal change looks like
# across our longitudinal dataset.
# ------------------------------------------------------------

change_model = IsolationForest(
    n_estimators=200,
    contamination="auto",
    random_state=42
)

change_model.fit(X_scaled)


# ------------------------------------------------------------
# 5. Generate model anomaly/change scores
#
# sklearn:
# lower decision_function = more unusual
#
# We reverse it so:
# higher score = more unusual multimodal change.
# ------------------------------------------------------------

model_df["model_change_score"] = (
    -change_model.decision_function(X_scaled)
)


# ------------------------------------------------------------
# 6. Convert score to prototype categories
#
# DATA-RELATIVE categories only.
# ------------------------------------------------------------

scores = model_df["model_change_score"]

low_threshold = np.percentile(scores, 33)
high_threshold = np.percentile(scores, 67)


def model_category(score):

    if score < low_threshold:
        return "LOW CHANGE"

    elif score < high_threshold:
        return "MODERATE CHANGE"

    else:
        return "HIGH CHANGE"


model_df["model_change_category"] = (
    model_df["model_change_score"]
    .apply(model_category)
)


# ------------------------------------------------------------
# 7. Show predictions
# ------------------------------------------------------------

results = (
    model_df[
        [
            "case",
            "previous_day",
            "current_day",
            "days_between",
            "model_change_score",
            "model_change_category"
        ]
    ]
    .sort_values(
        "model_change_score",
        ascending=False
    )
)


print("\n" + "=" * 70)
print("TRAINED MODEL OUTPUT")
print("=" * 70)

display(results.head(20))


# ------------------------------------------------------------
# 8. Save model artifacts
# ------------------------------------------------------------

MODEL_DIR = "/content/WoundLens_Model/models"

os.makedirs(
    MODEL_DIR,
    exist_ok=True
)


joblib.dump(
    change_model,
    os.path.join(
        MODEL_DIR,
        "woundlens_change_model.pkl"
    )
)


joblib.dump(
    model_scaler,
    os.path.join(
        MODEL_DIR,
        "woundlens_scaler.pkl"
    )
)


joblib.dump(
    model_features,
    os.path.join(
        MODEL_DIR,
        "woundlens_features.pkl"
    )
)


joblib.dump(
    {
        "low_threshold": low_threshold,
        "high_threshold": high_threshold
    },
    os.path.join(
        MODEL_DIR,
        "woundlens_thresholds.pkl"
    )
)


# ------------------------------------------------------------
# 9. Final report
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("WOUNDLENS MODEL — TRAINING COMPLETE")
print("=" * 70)

print("Training comparisons :", len(model_df))
print("Patients represented :", model_df["case"].nunique())

print("\nSaved model:")
print(
    os.path.join(
        MODEL_DIR,
        "woundlens_change_model.pkl"
    )
)

print("\nMODEL ROLE:")
print(
    "Detect unusual/magnitude patterns of multimodal "
    "change between wound visits."
)

print("\nNOT CLAIMED:")
print(
    "Diagnosis, infection detection, tissue-depth healing, "
    "or clinically validated healing/worsening prediction."
)

# ============================================================
# WOUNDLENS MODEL — STEP 7
# PATIENT-LEVEL UNSEEN TEST
#
# Hold out case_12 completely.
#
# Train:
#   All other longitudinal patients
#
# Test:
#   case_12 only
#
# This prevents patient leakage.
# ============================================================

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest


# ------------------------------------------------------------
# 1. Choose completely unseen patient
# ------------------------------------------------------------

TEST_CASE = "case_12"


# Remove invalid same-day comparisons
valid_df = changes_df[
    changes_df["days_between"] > 0
].copy()


# ------------------------------------------------------------
# 2. Patient-level split
# ------------------------------------------------------------

train_df = valid_df[
    valid_df["case"] != TEST_CASE
].copy()

test_df = valid_df[
    valid_df["case"] == TEST_CASE
].copy()


print("=" * 70)
print("PATIENT-LEVEL TRAIN / TEST SPLIT")
print("=" * 70)

print("Training patients :", train_df["case"].nunique())
print("Training pairs    :", len(train_df))

print("\nUnseen test patient:", TEST_CASE)
print("Test pairs         :", len(test_df))


# ------------------------------------------------------------
# 3. Prepare features
# ------------------------------------------------------------

X_train = (
    train_df[model_features]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

X_test = (
    test_df[model_features]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)


# ------------------------------------------------------------
# 4. IMPORTANT:
# Fit scaler ONLY using training data.
#
# Test patient must not influence normalization.
# ------------------------------------------------------------

test_scaler = StandardScaler()

X_train_scaled = test_scaler.fit_transform(
    X_train
)

X_test_scaled = test_scaler.transform(
    X_test
)


# ------------------------------------------------------------
# 5. Train ONLY on other patients
# ------------------------------------------------------------

unseen_model = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42
)

unseen_model.fit(
    X_train_scaled
)


# ------------------------------------------------------------
# 6. Determine categories using TRAINING scores only
# ------------------------------------------------------------

train_scores = (
    -unseen_model.decision_function(
        X_train_scaled
    )
)

train_low = np.percentile(
    train_scores,
    33
)

train_high = np.percentile(
    train_scores,
    67
)


# ------------------------------------------------------------
# 7. Predict completely unseen patient
# ------------------------------------------------------------

test_scores = (
    -unseen_model.decision_function(
        X_test_scaled
    )
)

test_df[
    "unseen_model_score"
] = test_scores


def unseen_category(score):

    if score < train_low:
        return "LOW CHANGE"

    elif score < train_high:
        return "MODERATE CHANGE"

    else:
        return "HIGH CHANGE"


test_df[
    "unseen_change_category"
] = test_df[
    "unseen_model_score"
].apply(
    unseen_category
)


# ------------------------------------------------------------
# 8. Show unseen predictions
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("UNSEEN PATIENT MODEL OUTPUT")
print("=" * 70)

test_results = test_df[
    [
        "case",
        "previous_day",
        "current_day",
        "days_between",
        "unseen_model_score",
        "unseen_change_category"
    ]
].sort_values(
    "current_day"
)

display(
    test_results
)


# ------------------------------------------------------------
# 9. Training thresholds
# ------------------------------------------------------------

print("\nTraining-derived thresholds:")
print("Low/Moderate :", round(train_low, 4))
print("Moderate/High:", round(train_high, 4))


# ------------------------------------------------------------
# 10. Final report
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("WOUNDLENS — UNSEEN PATIENT TEST COMPLETE")
print("=" * 70)

print("Model trained without :", TEST_CASE)
print("Test patient          :", TEST_CASE)
print("Test comparisons      :", len(test_df))

print("\nDATA LEAKAGE:")
print("Patient-level separation : PASS")
print("Scaler fit on train only  : PASS")
print("Thresholds from train only: PASS")

print("\nINTERPRETATION:")
print(
    "The model estimates whether multimodal change in an "
    "unseen patient's follow-up is typical or unusual relative "
    "to longitudinal changes observed in training patients."
)

print("\nIMPORTANT:")
print(
    "HIGH CHANGE means unusual/large multimodal change.\n"
    "It does NOT mean clinically worsening."
)

# ============================================================
# DOWNLOAD WOUNDLENS MODEL PACKAGE
# ============================================================

import shutil
from google.colab import files

MODEL_DIR = "/content/WoundLens_Model/models"

# Package model + scaler + features + thresholds
shutil.make_archive(
    "/content/woundlens_model",
    "zip",
    MODEL_DIR
)

print("Model package created:")
print("/content/woundlens_model.zip")

files.download(
    "/content/woundlens_model.zip"
)

!pip install -q trimesh
print("trimesh installed")

import trimesh
print("READY FOR 3D ANALYSIS")

# ============================================================
# WOUNDLENS — STEP 8
# Create a visual multimodal + 3D wound analysis for one visit
#
# Goal:
# 1. Load RGB, thermal, and depth-mesh point cloud
# 2. Manually select wound ROI on RGB image
# 3. Highlight corresponding approximate region
# 4. Show RGB + Thermal + 3D side by side
#
# IMPORTANT:
# - This is a prototype ROI selection
# - We are NOT yet claiming exact clinical depth
# - We are NOT predicting infection or surgery need
# ============================================================

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import trimesh

# ------------------------------------------------------------
# 1. Choose one demo visit
# ------------------------------------------------------------

CASE = "case_12"
DAY = "day_1"

CASE_ROOT = f"/content/WoundLens_Model/dataset/results/{CASE}/{DAY}"

# Find scene folder automatically
scene_path = None

for root, dirs, files in os.walk(CASE_ROOT):
    if os.path.basename(root).startswith("scene_"):
        if "photo.png" in files and "thermal.png" in files and "depth-mesh.ply" in files:
            scene_path = root
            break

if scene_path is None:
    raise FileNotFoundError(
        f"No valid multimodal scene found for {CASE} {DAY}"
    )

print("Using scene:")
print(scene_path)


# ------------------------------------------------------------
# 2. Load RGB and thermal images
# ------------------------------------------------------------

rgb_path = os.path.join(scene_path, "photo.png")
thermal_path = os.path.join(scene_path, "thermal.png")
mesh_path = os.path.join(scene_path, "depth-mesh.ply")

rgb_bgr = cv2.imread(rgb_path)
thermal_bgr = cv2.imread(thermal_path)

if rgb_bgr is None or thermal_bgr is None:
    raise ValueError("Could not load RGB or thermal image.")

rgb = cv2.cvtColor(rgb_bgr, cv2.COLOR_BGR2RGB)
thermal = cv2.cvtColor(thermal_bgr, cv2.COLOR_BGR2RGB)


# ------------------------------------------------------------
# 3. MANUAL ROI FOR PROTOTYPE
#
# IMPORTANT:
# Adjust these values after looking at the RGB image.
#
# Format:
# x_min, y_min, x_max, y_max
#
# Start with these and change if needed.
# ------------------------------------------------------------

ROI = {
    "x_min": 180,
    "y_min": 70,
    "x_max": 280,
    "y_max": 190,
}

x1 = ROI["x_min"]
y1 = ROI["y_min"]
x2 = ROI["x_max"]
y2 = ROI["y_max"]


# ------------------------------------------------------------
# 4. Draw wound ROI on RGB
# ------------------------------------------------------------

rgb_roi = rgb.copy()

cv2.rectangle(
    rgb_roi,
    (x1, y1),
    (x2, y2),
    (255, 0, 0),
    3
)


# ------------------------------------------------------------
# 5. Load 3D point cloud
# ------------------------------------------------------------

geometry = trimesh.load(
    mesh_path,
    process=False
)

if not hasattr(geometry, "vertices"):
    raise ValueError("PLY does not contain vertices.")

vertices = np.asarray(geometry.vertices)

print("3D points:", len(vertices))


# ------------------------------------------------------------
# 6. Get point colors if available
# ------------------------------------------------------------

point_colors = None

if hasattr(geometry, "colors"):
    colors = np.asarray(geometry.colors)

    if len(colors) == len(vertices):
        point_colors = colors[:, :3] / 255.0


# ------------------------------------------------------------
# 7. Create 3D visualization
#
# NOTE:
# We do NOT yet have an exact RGB-pixel -> point-cloud mapping.
#
# Therefore this view shows the full captured 3D surface.
# The ROI on the RGB image identifies the wound visually.
#
# Exact wound point isolation comes after segmentation +
# camera projection/calibration mapping.
# ------------------------------------------------------------

x = vertices[:, 0]
y = vertices[:, 1]
z = vertices[:, 2]

# Remove extreme outliers only for visualization
z_low = np.percentile(z, 2)
z_high = np.percentile(z, 98)

valid = (z >= z_low) & (z <= z_high)

x_plot = x[valid]
y_plot = y[valid]
z_plot = z[valid]

if point_colors is not None:
    color_plot = point_colors[valid]
else:
    color_plot = z_plot


# ------------------------------------------------------------
# 8. Create multimodal dashboard
# ------------------------------------------------------------

fig = plt.figure(
    figsize=(18, 6)
)

# ---------------- RGB ----------------
ax1 = fig.add_subplot(1, 3, 1)

ax1.imshow(rgb_roi)

ax1.set_title(
    f"{CASE} {DAY}\nRGB + Prototype Wound ROI",
    fontsize=14,
    fontweight="bold"
)

ax1.axis("off")


# ---------------- THERMAL ----------------
ax2 = fig.add_subplot(1, 3, 2)

ax2.imshow(thermal)

ax2.set_title(
    "Thermal View",
    fontsize=14,
    fontweight="bold"
)

ax2.axis("off")


# ---------------- 3D ----------------
ax3 = fig.add_subplot(
    1,
    3,
    3,
    projection="3d"
)

ax3.scatter(
    x_plot,
    y_plot,
    z_plot,
    c=color_plot,
    s=2
)

ax3.set_title(
    "3D Surface Geometry",
    fontsize=14,
    fontweight="bold"
)

ax3.set_xlabel("X")
ax3.set_ylabel("Y")
ax3.set_zlabel("Z")

ax3.invert_yaxis()

ax3.view_init(
    elev=35,
    azim=-65
)


# ------------------------------------------------------------
# 9. Final title
# ------------------------------------------------------------

fig.suptitle(
    "WoundLens — Multimodal Wound Assessment",
    fontsize=20,
    fontweight="bold"
)

plt.tight_layout(
    rect=[0, 0, 1, 0.92]
)


# ------------------------------------------------------------
# 10. Save
# ------------------------------------------------------------

OUTPUT = (
    "/content/WoundLens_Model/"
    f"{CASE}_{DAY}_multimodal_3d.png"
)

plt.savefig(
    OUTPUT,
    dpi=200,
    bbox_inches="tight"
)

plt.show()

print("\nSaved:")
print(OUTPUT)


# ------------------------------------------------------------
# 11. Final status
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("WOUNDLENS — STEP 8 COMPLETE")
print("=" * 60)

print("RGB        : PASS")
print("Thermal    : PASS")
print("3D surface : PASS")

print("\nNOTE:")
print(
    "The wound ROI is manually initialized for this prototype.\n"
    "Exact automatic wound segmentation and 3D ROI mapping are "
    "future/next-step components."
)

# ============================================================
# WOUNDLENS — STEP 9 (COLAB-SAFE)
# Create and visually verify wound mask
#
# No ipympl / interactive backend required.
# ============================================================

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# 1. Load Case 12 / Day 1
# ------------------------------------------------------------

CASE = "case_12"
DAY = "day_1"

CASE_ROOT = f"/content/WoundLens_Model/dataset/results/{CASE}/{DAY}"

scene_path = None

for root, dirs, files in os.walk(CASE_ROOT):
    if (
        os.path.basename(root).startswith("scene_")
        and "photo.png" in files
    ):
        scene_path = root
        break

if scene_path is None:
    raise FileNotFoundError("Scene not found.")

rgb_bgr = cv2.imread(
    os.path.join(scene_path, "photo.png")
)

rgb = cv2.cvtColor(
    rgb_bgr,
    cv2.COLOR_BGR2RGB
)

height, width = rgb.shape[:2]

print("Image size:", width, "x", height)
print("Scene:", scene_path)


# ------------------------------------------------------------
# 2. Prototype wound polygon
#
# These points surround the visible ulcer in case_12/day_1.
# We will VERIFY the result visually before doing any 3D work.
# ------------------------------------------------------------

# ============================================================
# CASE 12 / DAY 1 — TIGHT OPEN-WOUND MASK
# ============================================================

polygon = np.array([
    [105, 103],
    [119, 96],
    [137, 99],
    [151, 108],
    [161, 121],
    [160, 137],
    [151, 151],
    [137, 162],
    [119, 169],
    [102, 166],
    [91, 156],
    [87, 143],
    [91, 127],
    [98, 113]
], dtype=np.int32)

# ------------------------------------------------------------
# 3. Create binary wound mask
# ------------------------------------------------------------

wound_mask = np.zeros(
    (height, width),
    dtype=np.uint8
)

cv2.fillPoly(
    wound_mask,
    [polygon],
    255
)


# ------------------------------------------------------------
# 4. Create boundary overlay
# ------------------------------------------------------------

overlay = rgb.copy()

cv2.polylines(
    overlay,
    [polygon],
    True,
    (0, 255, 255),
    3
)


# ------------------------------------------------------------
# 5. Add transparent wound highlight
# ------------------------------------------------------------

highlight = overlay.copy()

highlight[wound_mask > 0] = [255, 0, 0]

overlay = cv2.addWeighted(
    overlay,
    0.70,
    highlight,
    0.30,
    0
)


# ------------------------------------------------------------
# 6. Display for verification
# ------------------------------------------------------------

fig, axes = plt.subplots(
    1,
    3,
    figsize=(16, 5)
)

axes[0].imshow(rgb)
axes[0].set_title("Original RGB")
axes[0].axis("off")

axes[1].imshow(
    wound_mask,
    cmap="gray"
)
axes[1].set_title("Prototype Wound Mask")
axes[1].axis("off")

axes[2].imshow(overlay)
axes[2].set_title("Wound Boundary Verification")
axes[2].axis("off")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 7. Save
# ------------------------------------------------------------

OUTPUT_DIR = "/content/WoundLens_Model/wound_masks"

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

MASK_PATH = os.path.join(
    OUTPUT_DIR,
    f"{CASE}_{DAY}_mask.png"
)

OVERLAY_PATH = os.path.join(
    OUTPUT_DIR,
    f"{CASE}_{DAY}_overlay.png"
)

cv2.imwrite(
    MASK_PATH,
    wound_mask
)

cv2.imwrite(
    OVERLAY_PATH,
    cv2.cvtColor(
        overlay,
        cv2.COLOR_RGB2BGR
    )
)


# ------------------------------------------------------------
# 8. Statistics
# ------------------------------------------------------------

wound_pixels = np.sum(
    wound_mask > 0
)

relative_area = (
    wound_pixels /
    (height * width)
) * 100


print("\n" + "=" * 60)
print("WOUNDLENS — STEP 9 COMPLETE")
print("=" * 60)

print("Wound pixels :", wound_pixels)

print(
    "Image area   :",
    round(relative_area, 2),
    "%"
)

print("\nMask saved:")
print(MASK_PATH)

print("\nOverlay saved:")
print(OVERLAY_PATH)

# ============================================================
# WOUNDLENS — STEP 9C
# Automatic wound-bed extraction using GrabCut
#
# Goal:
# Broad ROI -> automatic wound segmentation -> cleaned mask
#
# This is still prototype segmentation, but much better than
# manually guessing polygon coordinates.
# ============================================================

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# 1. Load Case 12 / Day 1 RGB
# ------------------------------------------------------------

CASE = "case_12"
DAY = "day_1"

CASE_ROOT = f"/content/WoundLens_Model/dataset/results/{CASE}/{DAY}"

scene_path = None

for root, dirs, files in os.walk(CASE_ROOT):
    if (
        os.path.basename(root).startswith("scene_")
        and "photo.png" in files
    ):
        scene_path = root
        break

if scene_path is None:
    raise FileNotFoundError("Scene not found.")

rgb_bgr = cv2.imread(
    os.path.join(scene_path, "photo.png")
)

if rgb_bgr is None:
    raise ValueError("photo.png could not be loaded.")

rgb = cv2.cvtColor(
    rgb_bgr,
    cv2.COLOR_BGR2RGB
)

h, w = rgb.shape[:2]

print("Image size:", w, "x", h)
print("Scene:", scene_path)


# ------------------------------------------------------------
# 2. BROAD rectangle around the ENTIRE visible wound
#
# Format:
# x, y, width, height
#
# This is deliberately larger than the wound.
# GrabCut will refine inside it.
# ------------------------------------------------------------

rect = (
    20,    # x
    85,    # y
    155,   # width
    110    # height
)


# ------------------------------------------------------------
# 3. Initialize GrabCut
# ------------------------------------------------------------

grabcut_mask = np.zeros(
    (h, w),
    np.uint8
)

bg_model = np.zeros(
    (1, 65),
    np.float64
)

fg_model = np.zeros(
    (1, 65),
    np.float64
)


cv2.grabCut(
    rgb_bgr,
    grabcut_mask,
    rect,
    bg_model,
    fg_model,
    8,
    cv2.GC_INIT_WITH_RECT
)


# ------------------------------------------------------------
# 4. Convert GrabCut labels into binary foreground mask
# ------------------------------------------------------------

binary = np.where(
    (grabcut_mask == cv2.GC_FGD) |
    (grabcut_mask == cv2.GC_PR_FGD),
    255,
    0
).astype("uint8")


# ------------------------------------------------------------
# 5. Restrict segmentation to wound search region
#
# Prevents GrabCut from selecting unrelated parts of the image.
# ------------------------------------------------------------

roi_mask = np.zeros_like(binary)

x, y, rw, rh = rect

roi_mask[
    y:y + rh,
    x:x + rw
] = 255

binary = cv2.bitwise_and(
    binary,
    roi_mask
)


# ------------------------------------------------------------
# 6. Morphological cleanup
#
# Remove tiny noise and fill small gaps.
# ------------------------------------------------------------

kernel = np.ones(
    (5, 5),
    np.uint8
)

binary = cv2.morphologyEx(
    binary,
    cv2.MORPH_OPEN,
    kernel,
    iterations=1
)

binary = cv2.morphologyEx(
    binary,
    cv2.MORPH_CLOSE,
    kernel,
    iterations=2
)


# ------------------------------------------------------------
# 7. Connected components
#
# Keep meaningful components inside the wound region.
# Do NOT blindly keep the largest region if it becomes the leg.
# ------------------------------------------------------------

num_labels, labels, stats, centroids = (
    cv2.connectedComponentsWithStats(
        binary,
        connectivity=8
    )
)

clean_mask = np.zeros_like(binary)

# We expect the wound around the left-middle/lower area.
target_center = np.array([
    95,   # expected x center
    135   # expected y center
])


best_score = None
best_label = None

for label_id in range(1, num_labels):

    area = stats[
        label_id,
        cv2.CC_STAT_AREA
    ]

    if area < 150:
        continue

    cx, cy = centroids[label_id]

    center = np.array([cx, cy])

    distance = np.linalg.norm(
        center - target_center
    )

    # Prefer:
    # - reasonably large regions
    # - regions close to the expected wound location
    score = area / (1 + distance)

    if best_score is None or score > best_score:
        best_score = score
        best_label = label_id


if best_label is not None:
    clean_mask[
        labels == best_label
    ] = 255
else:
    print("WARNING: No suitable wound component detected.")
    clean_mask = binary.copy()


# ------------------------------------------------------------
# 8. Extract contour
# ------------------------------------------------------------

contours, _ = cv2.findContours(
    clean_mask,
    cv2.RETR_EXTERNAL,
    cv2.CHAIN_APPROX_SIMPLE
)

overlay = rgb.copy()

if contours:

    largest_contour = max(
        contours,
        key=cv2.contourArea
    )

    cv2.drawContours(
        overlay,
        [largest_contour],
        -1,
        (0, 255, 255),
        3
    )


# ------------------------------------------------------------
# 9. Transparent wound highlight
# ------------------------------------------------------------

highlighted = overlay.copy()

highlighted[
    clean_mask > 0
] = [255, 50, 50]

overlay = cv2.addWeighted(
    overlay,
    0.72,
    highlighted,
    0.28,
    0
)


# ------------------------------------------------------------
# 10. Display
# ------------------------------------------------------------

fig, axes = plt.subplots(
    1,
    4,
    figsize=(19, 5)
)


# Original
axes[0].imshow(rgb)
axes[0].set_title("Original RGB")
axes[0].axis("off")


# Broad search region
rect_view = rgb.copy()

cv2.rectangle(
    rect_view,
    (x, y),
    (x + rw, y + rh),
    (255, 255, 0),
    2
)

axes[1].imshow(rect_view)
axes[1].set_title("Wound Search Region")
axes[1].axis("off")


# Binary wound mask
axes[2].imshow(
    clean_mask,
    cmap="gray"
)

axes[2].set_title("Detected Wound Mask")
axes[2].axis("off")


# Final verification
axes[3].imshow(overlay)
axes[3].set_title("Detected Wound Boundary")
axes[3].axis("off")


plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 11. Save
# ------------------------------------------------------------

OUTPUT_DIR = (
    "/content/WoundLens_Model/wound_masks"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

MASK_PATH = os.path.join(
    OUTPUT_DIR,
    f"{CASE}_{DAY}_auto_mask.png"
)

OVERLAY_PATH = os.path.join(
    OUTPUT_DIR,
    f"{CASE}_{DAY}_auto_overlay.png"
)

cv2.imwrite(
    MASK_PATH,
    clean_mask
)

cv2.imwrite(
    OVERLAY_PATH,
    cv2.cvtColor(
        overlay,
        cv2.COLOR_RGB2BGR
    )
)


# ------------------------------------------------------------
# 12. Report
# ------------------------------------------------------------

wound_pixels = int(
    np.sum(clean_mask > 0)
)

relative_area = (
    wound_pixels /
    (h * w)
) * 100


print("\n" + "=" * 65)
print("WOUNDLENS — AUTOMATIC SEGMENTATION COMPLETE")
print("=" * 65)

print("Wound pixels:", wound_pixels)

print(
    "Relative image area:",
    round(relative_area, 2),
    "%"
)

print("\nMask:")
print(MASK_PATH)

print("\nOverlay:")
print(OVERLAY_PATH)

# ============================================================
# WOUNDLENS — STEP 10
# Wound-only 3D relative depth visualization
#
# Uses:
#   - automatic wound mask
#   - registered depth.png
#   - RGB image
#   - thermal image
#
# IMPORTANT:
# The Z values below represent RELATIVE DEPTH IMAGE VALUES.
# They are NOT millimeters and NOT internal tissue depth.
# ============================================================

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

CASE = "case_12"
DAY = "day_1"

SCENE_PATH = (
    "/content/WoundLens_Model/dataset/results/"
    f"{CASE}/{DAY}/results/scene_1"
)

MASK_PATH = (
    "/content/WoundLens_Model/wound_masks/"
    f"{CASE}_{DAY}_auto_mask.png"
)

RGB_PATH = os.path.join(
    SCENE_PATH,
    "photo.png"
)

THERMAL_PATH = os.path.join(
    SCENE_PATH,
    "thermal.png"
)

DEPTH_PATH = os.path.join(
    SCENE_PATH,
    "depth.png"
)

# ------------------------------------------------------------
# 2. Load RGB, thermal, depth and wound mask
# ------------------------------------------------------------

rgb_bgr = cv2.imread(RGB_PATH)
thermal_bgr = cv2.imread(THERMAL_PATH)
depth_bgr = cv2.imread(DEPTH_PATH)
mask = cv2.imread(
    MASK_PATH,
    cv2.IMREAD_GRAYSCALE
)

if any(
    item is None
    for item in [
        rgb_bgr,
        thermal_bgr,
        depth_bgr,
        mask
    ]
):
    raise ValueError(
        "One or more required files could not be loaded."
    )

rgb = cv2.cvtColor(
    rgb_bgr,
    cv2.COLOR_BGR2RGB
)

thermal = cv2.cvtColor(
    thermal_bgr,
    cv2.COLOR_BGR2RGB
)

# Convert rendered depth image into one intensity channel.
depth_gray = cv2.cvtColor(
    depth_bgr,
    cv2.COLOR_BGR2GRAY
).astype(np.float32)

h, w = mask.shape

print("Image size:", w, "x", h)

# ------------------------------------------------------------
# 3. Extract wound pixels only
# ------------------------------------------------------------

wound_pixels = mask > 0

ys, xs = np.where(
    wound_pixels
)

z = depth_gray[
    wound_pixels
]

print(
    "Wound pixels:",
    len(z)
)

# ------------------------------------------------------------
# 4. Create RELATIVE depth
#
# Remove global camera-distance offset.
#
# Median depth within the wound region becomes the reference.
# This makes the visualization easier to interpret.
#
# Again:
# this is NOT physical millimeter depth.
# ------------------------------------------------------------

reference_depth = np.median(z)

relative_z = (
    z - reference_depth
)

# Clip extreme rendered-image values for better visualization.
low = np.percentile(
    relative_z,
    2
)

high = np.percentile(
    relative_z,
    98
)

keep = (
    (relative_z >= low)
    & (relative_z <= high)
)

x_plot = xs[keep]
y_plot = ys[keep]
z_plot = relative_z[keep]

# ------------------------------------------------------------
# 5. Basic relative-depth statistics
# ------------------------------------------------------------

relative_range = (
    float(np.max(z_plot))
    - float(np.min(z_plot))
)

mean_relative = float(
    np.mean(
        np.abs(z_plot)
    )
)

std_relative = float(
    np.std(z_plot)
)

# These are image-depth units only.
print("\nRELATIVE DEPTH FEATURES")
print("-" * 50)

print(
    "Relative depth range:",
    round(relative_range, 2)
)

print(
    "Mean absolute variation:",
    round(mean_relative, 2)
)

print(
    "Depth variation std:",
    round(std_relative, 2)
)

# ------------------------------------------------------------
# 6. Create RGB wound overlay
# ------------------------------------------------------------

contours, _ = cv2.findContours(
    mask,
    cv2.RETR_EXTERNAL,
    cv2.CHAIN_APPROX_SIMPLE
)

rgb_overlay = rgb.copy()

cv2.drawContours(
    rgb_overlay,
    contours,
    -1,
    (0, 255, 255),
    2
)

# ------------------------------------------------------------
# 7. Create dashboard
# ------------------------------------------------------------

fig = plt.figure(
    figsize=(19, 6)
)

# ---------------- RGB ----------------

ax1 = fig.add_subplot(
    1,
    4,
    1
)

ax1.imshow(
    rgb_overlay
)

ax1.set_title(
    "RGB + Wound Region",
    fontweight="bold"
)

ax1.axis("off")

# ---------------- Thermal ----------------

ax2 = fig.add_subplot(
    1,
    4,
    2
)

ax2.imshow(
    thermal
)

ax2.set_title(
    "Thermal View",
    fontweight="bold"
)

ax2.axis("off")

# ---------------- 2D relative depth ----------------

ax3 = fig.add_subplot(
    1,
    4,
    3
)

depth_only = np.full(
    (h, w),
    np.nan,
    dtype=np.float32
)

depth_only[
    wound_pixels
] = (
    depth_gray[wound_pixels]
    - reference_depth
)

im = ax3.imshow(
    depth_only,
    cmap="viridis"
)

ax3.set_title(
    "Wound Relative Depth Map",
    fontweight="bold"
)

ax3.axis("off")

plt.colorbar(
    im,
    ax=ax3,
    fraction=0.046,
    pad=0.04,
    label="Relative depth value"
)

# ---------------- 3D wound surface ----------------

ax4 = fig.add_subplot(
    1,
    4,
    4,
    projection="3d"
)

scatter = ax4.scatter(
    x_plot,
    y_plot,
    z_plot,
    c=z_plot,
    cmap="viridis",
    s=5
)

ax4.set_title(
    "3D Wound Surface",
    fontweight="bold"
)

ax4.set_xlabel("X")
ax4.set_ylabel("Y")
ax4.set_zlabel(
    "Relative depth"
)

# Match image orientation.
ax4.invert_yaxis()

# Better visual angle.
ax4.view_init(
    elev=35,
    azim=-60
)

# ------------------------------------------------------------
# 8. Main title
# ------------------------------------------------------------

fig.suptitle(
    "WoundLens — Multimodal Structural Assessment",
    fontsize=19,
    fontweight="bold"
)

plt.tight_layout(
    rect=[0, 0, 1, 0.92]
)

# ------------------------------------------------------------
# 9. Save
# ------------------------------------------------------------

OUTPUT_PATH = (
    "/content/WoundLens_Model/"
    f"{CASE}_{DAY}_wound_3d_analysis.png"
)

plt.savefig(
    OUTPUT_PATH,
    dpi=200,
    bbox_inches="tight"
)

plt.show()

# ------------------------------------------------------------
# 10. Final report
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("WOUNDLENS — STEP 10 COMPLETE")
print("=" * 65)

print("Wound segmentation : PASS")
print("Thermal view       : PASS")
print("Relative depth map : PASS")
print("3D wound surface   : PASS")

print(
    "\nRelative depth range:",
    round(relative_range, 2)
)

print(
    "Depth variation:",
    round(std_relative, 2)
)

print("\nSaved:")
print(OUTPUT_PATH)

print("\nIMPORTANT:")
print(
    "These are relative registered depth-image measurements.\n"
    "They must NOT be reported as millimeters or as depth of "
    "infection into muscle/tissue."
)

# Download the already-created WoundLens model package
from google.colab import files

files.download('/content/WoundLens_Model/woundlens_model.zip')

# ============================================================
# WOUNDLENS — PACKAGE TRAINED MODEL
# ============================================================

import os
import zipfile

MODEL_DIR = "/content/WoundLens_Model/models"
ZIP_PATH = "/content/woundlens_trained_model.zip"

# Files required for inference
required_files = [
    "woundlens_change_model.pkl",
    "woundlens_features.pkl",
    "woundlens_scaler.pkl",
    "woundlens_thresholds.pkl"
]

print("Checking trained model files...\n")

# Verify everything exists BEFORE creating ZIP
for filename in required_files:
    path = os.path.join(MODEL_DIR, filename)

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing model file: {path}"
        )

    print("FOUND:", filename)


# Create ZIP
with zipfile.ZipFile(
    ZIP_PATH,
    "w",
    zipfile.ZIP_DEFLATED
) as zipf:

    for filename in required_files:

        full_path = os.path.join(
            MODEL_DIR,
            filename
        )

        zipf.write(
            full_path,
            arcname=filename
        )


print("\n" + "=" * 60)
print("WOUNDLENS MODEL PACKAGE READY")
print("=" * 60)

print("Saved:")
print(ZIP_PATH)

print(
    "Size:",
    round(os.path.getsize(ZIP_PATH) / 1024, 2),
    "KB"
)

# ============================================================
# WOUNDLENS — SAVED MODEL VERIFICATION (CORRECTED)
#
# The model artifacts were saved using joblib.dump(),
# so they must be loaded using joblib.load().
# ============================================================

import os
import joblib

MODEL_DIR = "/content/WoundLens_Model/models"

paths = {
    "model": os.path.join(
        MODEL_DIR,
        "woundlens_change_model.pkl"
    ),
    "scaler": os.path.join(
        MODEL_DIR,
        "woundlens_scaler.pkl"
    ),
    "features": os.path.join(
        MODEL_DIR,
        "woundlens_features.pkl"
    ),
    "thresholds": os.path.join(
        MODEL_DIR,
        "woundlens_thresholds.pkl"
    )
}

loaded = {}

print("=" * 65)
print("LOADING WOUNDLENS TRAINED MODEL")
print("=" * 65)

for name, path in paths.items():

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing: {path}"
        )

    loaded[name] = joblib.load(path)

    print(
        f"{name.upper():12s}: LOADED  "
        f"{type(loaded[name])}"
    )


# ------------------------------------------------------------
# Extract model components
# ------------------------------------------------------------

model = loaded["model"]
scaler = loaded["scaler"]
feature_names = loaded["features"]
thresholds = loaded["thresholds"]


# ------------------------------------------------------------
# Show information
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("WOUNDLENS — MODEL VERIFICATION PASSED")
print("=" * 65)

print(
    "\nNumber of expected features:",
    len(feature_names)
)

print("\nModel features:")

for i, feature in enumerate(
    feature_names,
    start=1
):
    print(
        f"{i:02d}. {feature}"
    )


print("\nThresholds:")
print(thresholds)

print("\nModel:")
print(model)

print("\nScaler:")
print(scaler)


print("\n" + "=" * 65)
print("READY FOR INFERENCE")
print("=" * 65)

# ============================================================
# WOUNDLENS — FINAL INFERENCE FUNCTION
#
# INPUT:
#   previous visit scene path
#   current visit scene path
#
# OUTPUT:
#   change score
#   LOW / MODERATE / HIGH
#   RGB / thermal / depth change summaries
#
# IMPORTANT:
# This is a longitudinal change model.
# It does NOT output healing probability or surgery need.
# ============================================================

import os
import cv2
import joblib
import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. Load saved model artifacts
# ------------------------------------------------------------

MODEL_DIR = "/content/WoundLens_Model/models"

change_model = joblib.load(
    os.path.join(MODEL_DIR, "woundlens_change_model.pkl")
)

scaler = joblib.load(
    os.path.join(MODEL_DIR, "woundlens_scaler.pkl")
)

model_features = joblib.load(
    os.path.join(MODEL_DIR, "woundlens_features.pkl")
)

thresholds = joblib.load(
    os.path.join(MODEL_DIR, "woundlens_thresholds.pkl")
)


# ------------------------------------------------------------
# 2. Extract raw visit features
# ------------------------------------------------------------

def extract_visit_features(scene_path):
    """
    Extract exactly the same RGB, thermal and depth features
    that were used during model training.
    """

    rgb_path = os.path.join(scene_path, "photo.png")
    thermal_path = os.path.join(scene_path, "thermal.png")
    depth_path = os.path.join(scene_path, "depth.png")

    rgb_bgr = cv2.imread(rgb_path)
    thermal_bgr = cv2.imread(thermal_path)
    depth_bgr = cv2.imread(depth_path)

    if rgb_bgr is None:
        raise FileNotFoundError(f"Missing RGB: {rgb_path}")

    if thermal_bgr is None:
        raise FileNotFoundError(f"Missing thermal: {thermal_path}")

    if depth_bgr is None:
        raise FileNotFoundError(f"Missing depth: {depth_path}")

    rgb = cv2.cvtColor(
        rgb_bgr,
        cv2.COLOR_BGR2RGB
    )

    thermal = cv2.cvtColor(
        thermal_bgr,
        cv2.COLOR_BGR2GRAY
    )

    depth = cv2.cvtColor(
        depth_bgr,
        cv2.COLOR_BGR2GRAY
    )

    r = rgb[:, :, 0]
    g = rgb[:, :, 1]
    b = rgb[:, :, 2]

    return {
        "rgb_r_mean": float(np.mean(r)),
        "rgb_g_mean": float(np.mean(g)),
        "rgb_b_mean": float(np.mean(b)),

        "rgb_r_std": float(np.std(r)),
        "rgb_g_std": float(np.std(g)),
        "rgb_b_std": float(np.std(b)),

        "thermal_mean": float(np.mean(thermal)),
        "thermal_std": float(np.std(thermal)),
        "thermal_p25": float(np.percentile(thermal, 25)),
        "thermal_p50": float(np.percentile(thermal, 50)),
        "thermal_p75": float(np.percentile(thermal, 75)),

        "depth_mean": float(np.mean(depth)),
        "depth_std": float(np.std(depth)),
        "depth_p25": float(np.percentile(depth, 25)),
        "depth_p50": float(np.percentile(depth, 50)),
        "depth_p75": float(np.percentile(depth, 75)),
    }


# ------------------------------------------------------------
# 3. Calculate previous -> current percentage changes
# ------------------------------------------------------------

def build_change_features(previous, current):
    """
    Convert two visit feature dictionaries into the exact
    percentage-change features expected by the trained model.
    """

    output = {}

    base_features = [
        "rgb_r_mean",
        "rgb_g_mean",
        "rgb_b_mean",
        "rgb_r_std",
        "rgb_g_std",
        "rgb_b_std",

        "thermal_mean",
        "thermal_std",
        "thermal_p25",
        "thermal_p50",
        "thermal_p75",

        "depth_mean",
        "depth_std",
        "depth_p25",
        "depth_p50",
        "depth_p75",
    ]

    for feature in base_features:

        prev_value = float(previous[feature])
        curr_value = float(current[feature])

        denominator = (
            abs(prev_value)
            if abs(prev_value) > 1e-6
            else 1e-6
        )

        pct_change = (
            (curr_value - prev_value)
            / denominator
        ) * 100.0

        output[
            f"{feature}_pct_change"
        ] = pct_change

    return output


# ------------------------------------------------------------
# 4. Final inference function
# ------------------------------------------------------------

def analyze_followup(previous_scene, current_scene):
    """
    Analyze longitudinal multimodal change between two visits.
    """

    previous = extract_visit_features(
        previous_scene
    )

    current = extract_visit_features(
        current_scene
    )

    change_features = build_change_features(
        previous,
        current
    )

    # Keep exact training feature order.
    X = pd.DataFrame(
        [[change_features[name] for name in model_features]],
        columns=model_features
    )

    X_scaled = scaler.transform(X)

    # Higher = more unusual multimodal change.
    score = float(
        -change_model.decision_function(
            X_scaled
        )[0]
    )

    low_threshold = float(
        thresholds["low_threshold"]
    )

    high_threshold = float(
        thresholds["high_threshold"]
    )

    if score < low_threshold:
        category = "LOW CHANGE"

    elif score < high_threshold:
        category = "MODERATE CHANGE"

    else:
        category = "HIGH CHANGE"


    # --------------------------------------------------------
    # Helpful modality-level summaries for the UI
    # --------------------------------------------------------

    rgb_keys = [
        key for key in change_features
        if key.startswith("rgb_")
    ]

    thermal_keys = [
        key for key in change_features
        if key.startswith("thermal_")
    ]

    depth_keys = [
        key for key in change_features
        if key.startswith("depth_")
    ]


    def mean_abs(keys):
        return float(
            np.mean([
                abs(change_features[key])
                for key in keys
            ])
        )


    result = {
        "change_score": score,
        "change_level": category,

        "rgb_change_index":
            mean_abs(rgb_keys),

        "thermal_change_index":
            mean_abs(thermal_keys),

        "depth_change_index":
            mean_abs(depth_keys),

        "review_required":
            category == "HIGH CHANGE"
    }

    return result


print("WoundLens inference function ready.")

# ============================================================
# WOUNDLENS — TEST SAVED MODEL ON A REAL FOLLOW-UP
#
# Case 12:
# Day 124 -> Day 313
# ============================================================

previous_scene = (
    "/content/WoundLens_Model/dataset/results/"
    "case_12/day_124/results/scene_1"
)

current_scene = (
    "/content/WoundLens_Model/dataset/results/"
    "case_12/day_313/results/scene_1"
)

result = analyze_followup(
    previous_scene,
    current_scene
)

print("=" * 60)
print("WOUNDLENS FOLLOW-UP ANALYSIS")
print("=" * 60)

print(
    "Multimodal change :",
    result["change_level"]
)

print(
    "Model score       :",
    round(result["change_score"], 4)
)

print(
    "RGB change index  :",
    round(result["rgb_change_index"], 2)
)

print(
    "Thermal change    :",
    round(result["thermal_change_index"], 2)
)

print(
    "Depth change      :",
    round(result["depth_change_index"], 2)
)

print(
    "Review required   :",
    result["review_required"]
)

print("\nRaw result:")
print(result)
